// ── Palette generator ────────────────────────────────────────────────────
// Writes css/palette.css: every Tailwind colour family as CSS variables
// ("--tw-red-400: 248 113 113"), which tailwind.config.js compiles the
// utilities against. Two reasons:
//
//   1. The dark themes only differ in their grey scale, but the light themes
//      need the *semantic* colours re-tuned as well: text-green-400 is a pastel
//      meant for a dark page and bg-red-950/40 is a deep tint meant for one.
//      On light themes this file swaps the pastel stops (300/400) with the deep
//      ones (700/800) and the tints (50–200 ⇄ 800–950), so the same markup reads
//      correctly on both. 500 and 600 — the filled-button weights — stay put so
//      white-on-colour buttons keep their contrast.
//   2. Hand-written CSS and inline styles can reference the same variables and
//      follow the theme, instead of carrying their own hex codes.
//
// Run via `npm run build:css` (it runs first) or directly: node build-extras/gen-palette.js
const fs = require('fs');
const path = require('path');
const colors = require('tailwindcss/colors');

const FAMILIES = ['gray','zinc','neutral','stone','red','orange','amber','yellow','lime','green','emerald','teal','cyan','sky','blue','indigo','violet','purple','fuchsia','pink','rose'];
const STOPS = [50,100,200,300,400,500,600,700,800,900,950];
// Light-theme role swap. Anything not listed keeps its own value.
const LIGHT_SWAP = { 50: 950, 100: 900, 200: 800, 300: 700, 400: 600, 700: 300, 800: 200, 900: 100, 950: 50 };

const triplet = hex => [1,3,5].map(i => parseInt(hex.slice(i,i+2),16)).join(' ');

let dark = '', light = '';
for (const f of FAMILIES) {
    for (const s of STOPS) {
        dark  += `    --tw-${f}-${s}: ${triplet(colors[f][s])};\n`;
        if (LIGHT_SWAP[s]) light += `    --tw-${f}-${s}: ${triplet(colors[f][LIGHT_SWAP[s]])};\n`;
    }
}

const out = `/* Generated by build-extras/gen-palette.js — do not edit by hand.
   Tailwind's colour families as RGB-triplet variables. tailwind.config.js
   compiles every colour utility against these, so the light themes can
   re-tune the semantic colours (see the generator for the mapping). */
:root {
${dark}}
/* Light themes: pastel text stops swap with deep ones, tints swap with shades. */
:root[data-theme="light"] {
${light}}
`;
fs.writeFileSync(path.join(__dirname, '..', 'css', 'palette.css'), out);
console.log('css/palette.css written:', FAMILIES.length, 'families');
